[nfs]
172.31.38.143 ansible_ssh_user='ec2-user'

[webservers]
172.31.42.147 ansible_ssh_user='ec2-user'
172.31.36.152 ansible_ssh_user='ec2-user'

[db]
172.31.34.105 ansible_ssh_user='ubuntu' 

[lb]
172.31.34.209 ansible_ssh_user='ubuntu'